### ISSUE TITLE
Error Build

### ISSUE THREAD

**Issue by mrcarbook** [marklauter/TelloAPI#3]
Hi,
during the build i got error of missing reference about TelloEmulator and Tello.Messaging .
Regards

**Comment by marklauter** [comment]
Hi
Yeah, I screwed up and started a major refactor on the main branch.
To build the solution I have these projects unloaded:
- /samples/Tello.SDKV2.Emulator.Demo
- /src/Tello/Tello.Scripting
- /src/apps/Tello.App
- /src/apps/Tello.App.UWP

Based on my current progress I should have them all working again by this Sunday.

The newly refactored Tello.SDKV2.Demo is working with a live drone and should be a pretty good place to try out the command set.

**Comment by marklauter** [comment]
These two projects now build.
- /samples/Tello.SDKV2.Emulator.Demo
- /src/apps/Tello.App

**Comment by mrcarbook** [comment]
yes now are building.

**Comment by marklauter** [comment]
All projects in the solution now build.
